#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

#vim
bindkey -M viins 'jj' vi-cmd-mode

alias vi=vim

# exports
export SSH_ASKPASS=/usr/lib/ssh/x11-ssh-askpass
export GDK_SCALE=2
export GDK_DPI_SCALE=1

# ssh agent
alias sshadd="ssh-add ~/.ssh/id_rsa"

# PYTHON
export WORKON_HOME=~/.virtualenvs

# allow HEAD^ to be used in git
unsetopt nomatch

# task
alias task="vim ~/task"

# rename
alias cbz="perl-rename -i 's/\.zip$/\.cbz/' *.zip"
alias cbr="perl-rename -i 's/\.rar$/\.cbr/' *.rar"
